omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = [":cc-1.0.79", ":pkg-config-0.3.26"]
omit_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[extra_mapped_srcs]

[platform_fixup]
