omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = [":version_check-0.9.4"]
omit_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
[buildscript.rustc_flags]

[extra_mapped_srcs]

[platform_fixup]
