[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
derive_builder = { version = "0.12" }
futures = "0.3.13"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
si-data-nats = { path = "../../lib/si-data-nats" }
si-settings = { path = "../../lib/si-settings" }
telemetry = { path = "../../lib/telemetry-rs" }
thiserror = "1.0.24"
tokio = { version = "1.12.0", features = ["full"] }
ulid = { version = "1", features = ["serde"] }

# Local patches - typically git references
[patch.crates-io]
