omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = [":unicase-2.6.0"]
omit_deps = []
cargo_env = false

[env]
OUT_DIR = "generated"

[[buildscript]]
[buildscript.gen_srcs.mapped]
"mime_types_generated.rs" = "generated/mime_types_generated.rs"

[extra_mapped_srcs]

[platform_fixup]
